### ISSUE TITLE
"Missing required information of github package deborah"

### ISSUE THREAD

**Issue by KlfJoat** [wimpysworld/deb-get#1048]
Please make sure the version of `deb-get` you are using is up to date:

(excerpt)
```bash
...
Preparing to unpack .../deb-get_0.4.0-1_all.deb ...
Unpacking deb-get (0.4.0-1) over (0.4.0-1) ...
Setting up deb-get (0.4.0-1) ...
...
```
Done.

### Expected behavior

`deb-get update` is resilient against missing information in GitHub packages when the source website changes and the commands return no data or garbage data.

### Actual behavior

`deb-get update` throws an error because yet another package returns no data. This one is **`deborah`**, whatever that is.

```text
[!] ERROR! Missing required information of github package deborah:
URL=
VERSION_PUBLISHED=
```

**This error has existed for an unknown amount of time, because it was masked by the error in #997.**

This is a recurring problem (**#997** #962  #822) because `deb-get` doesn't gracefully handle the entirely foreseeable and obvious case where the fragile commands used to fill those variables returns nothing or returns garbage. It downloads data from external websites, not versioned APIs. Why is it not resilient against this? Why can't it WARN me and continue processing the rest of the package data? Updates still work, but installs don't. So now there are only **39** packages that users can install from scratch using `deb-get`.

```text
$ deb-get list                                                                      
1password                                      
activitywatch                                                                                       
agena                                                                                               
alduin                                                                                              
android-messages-desktop
antimicrox
anydesk
appimagelauncher
atom
atomic
atuin
audio-recorder
authme
azuredatastudio
balena-etcher
bat
battery-monitor
beersmith3
bitwarden
bitwig-studio
blanket
blockbench
bluejeans-v2
bottom
brave-browser
brisqi
browsh
caddy
caprine
cawbird
chronograf
code
codium
com.github.tkashkin.gamehub
copyq
cosign
croc
crossover
crow-translate
cryptomator
dbeaver-ce
deadbeef-static
deb-get                         [ installed ]
$
```

### Steps to reproduce

Run `deb-get update`. Look at error on screen.

### System information

Has not changed appreciably since #997, but I'll be glad to re-run if you think that has anything to do with this known and common error that you don't acknowledge, respond to Issues about, or say anything about like "hey, a fix is coming!"

Should we expect 2 more months before this mole is whacked without fixing the mallet/game/whatever updating `deb-get` for resilience is in this metaphor?

**Comment by philclifford** [comment]
Already fixed by #1027. 
Also `deborah`  definition is fine with the latest release version as well as the HEAD of `main`

```
$ ./deb-get show deborah
 
Deborah
  Package:	deborah
  Repository:	01-main
  Updater:	deb-get
  Installed:	No
  Published:	1.1.5
  Architecture:	amd64
  Download:	https://github.com/ymauray/deborah/releases/download/v1.1.5/deborah_1.1.5-1_jammy1.0_amd64.deb
  Website:	https://github.com/ymauray/deborah/
  Summary:	A Flutter front-end for deb-get.

**Comment by KlfJoat** [comment]
This is not a duplicate. 

Also, it is not fixed. This is still happening for me on 2 different hosts with `deb-get` v0.4.0, which is the latest version.

What other information do you need to help me troubleshoot this?

Any word on when the underlying & very foreseeable root cause of these whack-a-mole problems will be fixed?
