### ISSUE TITLE
input-leap: Missing URL & VERSION_PUBLISHED

### ISSUE THREAD

**Issue by rasa** [wimpysworld/deb-get#1458]
```
  [!] ERROR! Missing required information of github package input-leap:
URL=
VERSION_PUBLISHED=
```

Please assign this issue to me.

**Comment by rasa** [comment]
Current release doesn't include `.deb`s:

See https://github.com/input-leap/input-leap/releases

**Comment by sbstn87** [comment]
This should be fixed:

https://github.com/input-leap/input-leap/issues/2254

**Comment by shymega** [comment]
It's not fixed yet. That is a issue report, which is better tracked in https://github.com/input-leap/input-leap/issues/2259.

**Comment by philclifford** [comment]
As this is being dealt with upstream and we currently work ok with the latest published deb 
I'm closing this issue.

```
Input Leap
  Package:	input-leap
  Repository:	01-main
  Updater:	deb-get
  Installed:	No
  Published:	3.0.2
  Architecture:	amd64
  Download:	https://github.com/input-leap/input-leap/releases/download/v3.0.2/InputLeap_3.0.2_ubuntu_22-04_amd64.deb
  Website:	https://github.com/input-leap/input-leap
  Summary:	InputLeap allows you to share one mouse and keyboard between multiple computers. Work seamlessly across Windows, macOS and Linux.
```
