### ISSUE TITLE
Bug: Packages do not install on Debian 13: media-downloader, openrgb, veracrypt

### ISSUE THREAD

**Issue by sbstn87** [wimpysworld/deb-get#1628]
### Expected Behavior

All packages above should install on Debian 13.

### Actual Behavior

Some packages do not install on Debian 13, despite packages for it being available:
- media-downloader
- openrgb
- veracrypt

### /etc/os-release

```ini

```

### /etc/lsb-release

```ini

```

### deb-get version

```bash

```

### deb-get update

```bash

```

**Comment by flexiondotorg** [comment]
Resolved by recent PRs updating supported releases for media-downloader, openrgb, and veracrypt to include Debian 13 (trixie).

**Comment by sbstn87** [comment]
I still get this error when trying to install media-downloader:

ERROR! media-downloader is not supported on Debian Trixie.
