### ISSUE TITLE
prettylist in 0.3.2 is missing information from 0.3.1

### ISSUE THREAD

**Issue by GHMusicalCoder** [wimpysworld/deb-get#379]
### Expected behavior
prettylist printing out the app information properly

as an example: (audiorecorder app - from 0.3.1)
| [<img src=".github/launchpad.png" align="top" width="20" />](https://launchpad.net/~audio-recorder) | `audiorecorder` | <i>Audio recording app that allows for the recording from various sources such as microphones, a system's sound card, or a web browser, and save it to various possible formats.</i> |

### Actual behavior
as an example: (audiorecorder app - from 0.3.2)
| [<img src=".github/direct.png" align="top" width="20" />]() | `audiorecorder` | <i></i> |

### Steps to reproduce
deb-get prettylist

this is happening with the following apps:
- appimagelauncher
- audiorecorder
- blanket
- copyq
- cryptomator
- firefox-esr
- foliate
- fsearch
- gpu-viewer
- kdiskmark
- keepassxc
- lutris
- nextcloud-desktop
- obs-studio
- openrazer-meta
- papirus-icon-theme
- polychromatic
- quickemu
- quickgui
- strawberry
- ubuntu-make
- ulauncher
- xemu
- yq

### System information

Run the following a paste the output below:

#### /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

#### /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"

#### deb-get version
0.3.2

### deb-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
Hit:4 https://dl.google.com/linux/chrome/deb stable InRelease
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:6 https://brave-browser-apt-release.s3.brave.com stable InRelease
Get:7 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Hit:8 https://packages.riot.im/debian default InRelease
Ign:2 https://repo.vivaldi.com/stable/deb stable InRelease
Hit:9 https://repo.vivaldi.com/stable/deb stable Release
Fetched 324 kB in 1s (408 kB/s)
Reading package lists...
  [+] Updating /var/cache/deb-get/deb-get.json
  [+] Updating /var/cache/deb-get/lsd.json

**Comment by philclifford** [comment]
This is a symptom of and 
duplicates #365 
Fixed by #366

**Comment by flexiondotorg** [comment]
Fixed via fda249c4c482cdfb9d4031daec8e06fc8c7b80cf

**Comment by natanjunges** [comment]
https://github.com/wimpysworld/deb-get/commit/fda249c4c482cdfb9d4031daec8e06fc8c7b80cf does not fix this, as in distros that are not Ubuntu-based this will still happen.
